apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: australia-southeast1-docker.pkg.dev/sit323-24t1-jiakun-li-74d448a/node-app/node-app:v1
          ports:
            - containerPort: 8080
